// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// do_shrinkTVPVAR
List do_shrinkTVPVAR(arma::mat y_orig, arma::mat x_orig, std::string mod_type, int niter, int nburn, int nthin, bool display_progress, List TVP_param, List starting_vals);
RcppExport SEXP _shrinkTVPVAR_do_shrinkTVPVAR(SEXP y_origSEXP, SEXP x_origSEXP, SEXP mod_typeSEXP, SEXP niterSEXP, SEXP nburnSEXP, SEXP nthinSEXP, SEXP display_progressSEXP, SEXP TVP_paramSEXP, SEXP starting_valsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y_orig(y_origSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_orig(x_origSEXP);
    Rcpp::traits::input_parameter< std::string >::type mod_type(mod_typeSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    Rcpp::traits::input_parameter< int >::type nburn(nburnSEXP);
    Rcpp::traits::input_parameter< int >::type nthin(nthinSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    Rcpp::traits::input_parameter< List >::type TVP_param(TVP_paramSEXP);
    Rcpp::traits::input_parameter< List >::type starting_vals(starting_valsSEXP);
    rcpp_result_gen = Rcpp::wrap(do_shrinkTVPVAR(y_orig, x_orig, mod_type, niter, nburn, nthin, display_progress, TVP_param, starting_vals));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_shrinkTVPVAR_do_shrinkTVPVAR", (DL_FUNC) &_shrinkTVPVAR_do_shrinkTVPVAR, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_shrinkTVPVAR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
