# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

do_shrinkTVPVAR <- function(y_orig, x_orig, mod_type, niter, nburn, nthin, display_progress, TVP_param, starting_vals) {
    .Call(`_shrinkTVPVAR_do_shrinkTVPVAR`, y_orig, x_orig, mod_type, niter, nburn, nthin, display_progress, TVP_param, starting_vals)
}

